# Generated by Django 3.1.5 on 2021-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210123_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='unique_video_id',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ETag'),
        ),
    ]
